# Generated by Django 5.0.4 on 2024-04-28 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('disponible', models.BooleanField(default=True)),
                ('numero_de_jugadores', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField(default=django.utils.timezone.now)),
                ('hora_fin', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dado', models.CharField(choices=[('d6', 'Dado D6'), ('d8', 'Dado D8'), ('d10', 'Dado D10'), ('d12', 'Dado D12'), ('d20', 'Dado D20'), ('multi', 'Diversos dados')], default='d20', max_length=6)),
                ('base', models.CharField(choices=[('dnd5e', 'Dungeons & Dragons 5ª Edición'), ('dnd3e', 'Dungeons & Dragons 3ª Edición'), ('ff3e', 'Final Fantasy 3ª Edición'), ('whf', 'Warhammer Fantasy Roleplay'), ('wh40k', 'Warhammer 40.000 Roleplay'), ('marvel', 'Marvel Multiverse Role-Playing Game'), ('path', 'Pathfinder 2ª Edición'), ('cthul', 'Call of Cthulhu'), ('5ring', 'La Leyenda de los Cinco Anillos')], default='dnd5e', max_length=6)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('clase', models.CharField(max_length=50)),
                ('experiencia', models.BooleanField(default=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='partidas.juego')),
            ],
        ),
        migrations.AddField(
            model_name='juego',
            name='sistema_de_juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistema_de_juego', to='partidas.sistema'),
        ),
    ]
