# Generated by Django 5.0.4 on 2024-04-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0003_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='image',
            new_name='imagen',
        ),
    ]
