# Generated by Django 5.0.4 on 2024-04-30 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0005_rename_imagen_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='hora_fin',
            field=models.TimeField(default=datetime.datetime(2024, 4, 30, 0, 17, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='juego',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2024, 4, 30, 0, 17, tzinfo=datetime.timezone.utc)),
        ),
    ]
